model: 
  encoder:
    input:
      size: 50000
      dropout: 0
      normalize: true
      activation: ReLU
    hidden1: 
      size: 512
      dropout: null
      normalize: true
      activation: null
    hidden2: 
      size: 256
      dropout: null
      normalize: null
      activation: null
  decoder: 
    hidden2:
      size: 256
      dropout: 0
      normalize: true
      activation: ReLU
    hidden1:
      size: 512
      dropout: 0
      normalize: true
      activation: Sigmoid
    output:
      size: 50000
      dropout: null
      normalize: null
      activation: null

hyperparams:
  epochs: 3000
  batch_size: 128
  lr: 0.00001
  beta: 1
  weight_decay: 0